<?php

namespace Database\Seeders;

use App\Models\Company\CompanyEstablishmentContactsModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CompanyEstablishmentContactsSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0351', 'contact_2'=>'0351', 'type'=>'Principal', 'establishment_id'=>1,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0352', 'contact_2'=>'0352', 'type'=>'Interno', 'establishment_id'=>1,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Infocras', 'contact_1'=>'(81) 3101-0353', 'contact_2'=>'0353', 'type'=>'Interno', 'establishment_id'=>1,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Sala de Exames', 'contact_1'=>'(81) 3101-0356', 'contact_2'=>'0356', 'type'=>'Principal', 'establishment_id'=>2,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0405', 'contact_2'=>'0405', 'type'=>'Principal', 'establishment_id'=>3,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0354', 'contact_2'=>'0354', 'type'=>'Principal', 'establishment_id'=>4,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0355', 'contact_2'=>'0355', 'type'=>'Interno', 'establishment_id'=>4,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0409', 'contact_2'=>'0409', 'type'=>'Principal', 'establishment_id'=>5,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0274', 'contact_2'=>'0274', 'type'=>'Principal', 'establishment_id'=>6,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0390', 'contact_2'=>'0390', 'type'=>'Principal', 'establishment_id'=>7,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0360', 'contact_2'=>'0360', 'type'=>'Principal', 'establishment_id'=>9,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0361', 'contact_2'=>'0361', 'type'=>'Interno', 'establishment_id'=>9,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0366', 'contact_2'=>'0366', 'type'=>'Principal', 'establishment_id'=>10,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0367', 'contact_2'=>'0367', 'type'=>'Interno', 'establishment_id'=>10,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0207', 'contact_2'=>'0207', 'type'=>'Principal', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gerência', 'contact_1'=>'(81) 3101-0208', 'contact_2'=>'0208', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coordenação', 'contact_1'=>'(81) 3101-0209', 'contact_2'=>'0209', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0210', 'contact_2'=>'0210', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Odonto', 'contact_1'=>'(81) 3101-0211', 'contact_2'=>'0211', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Estoque Medicamentos', 'contact_1'=>'(81) 3101-0212', 'contact_2'=>'0212', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Estoque Material', 'contact_1'=>'(81) 3101-0213', 'contact_2'=>'0213', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Remédio na Porta', 'contact_1'=>'(81) 3101-0214', 'contact_2'=>'0214', 'type'=>'Interno', 'establishment_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0368', 'contact_2'=>'0368', 'type'=>'Principal', 'establishment_id'=>11,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0369', 'contact_2'=>'0369', 'type'=>'Principal', 'establishment_id'=>12,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0375', 'contact_2'=>'0375', 'type'=>'Principal', 'establishment_id'=>23,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0374', 'contact_2'=>'0374', 'type'=>'Principal', 'establishment_id'=>15,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0373', 'contact_2'=>'0373', 'type'=>'Principal', 'establishment_id'=>24,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0384', 'contact_2'=>'0384', 'type'=>'Principal', 'establishment_id'=>16,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0382', 'contact_2'=>'0382', 'type'=>'Principal', 'establishment_id'=>17,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0378', 'contact_2'=>'0378', 'type'=>'Principal', 'establishment_id'=>18,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0379', 'contact_2'=>'0379', 'type'=>'Interno', 'establishment_id'=>18,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0380', 'contact_2'=>'0380', 'type'=>'Principal', 'establishment_id'=>19,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0358', 'contact_2'=>'0358', 'type'=>'Principal', 'establishment_id'=>20,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0359', 'contact_2'=>'0359', 'type'=>'Interno', 'establishment_id'=>20,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0417', 'contact_2'=>'0417', 'type'=>'Principal', 'establishment_id'=>21,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gerência', 'contact_1'=>'(81) 3101-0235', 'contact_2'=>'0235', 'type'=>'Interno', 'establishment_id'=>98,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0345', 'contact_2'=>'0345', 'type'=>'Principal', 'establishment_id'=>25,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0376', 'contact_2'=>'0376', 'type'=>'Principal', 'establishment_id'=>26,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0210', 'contact_2'=>'0210', 'type'=>'Interno', 'establishment_id'=>27,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0306', 'contact_2'=>'0306', 'type'=>'Principal', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gerência', 'contact_1'=>'(81) 3101-0307', 'contact_2'=>'0307', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0308', 'contact_2'=>'0308', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Posto de Enfermagem II', 'contact_1'=>'(81) 3101-0309', 'contact_2'=>'0309', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Laboratório', 'contact_1'=>'(81) 3101-0310', 'contact_2'=>'0310', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Serviço Social', 'contact_1'=>'(81) 3101-0311', 'contact_2'=>'0311', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Nutrição', 'contact_1'=>'(81) 3101-0312', 'contact_2'=>'0312', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0313', 'contact_2'=>'0313', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CCIH', 'contact_1'=>'(81) 3101-0314', 'contact_2'=>'0314', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Pediatria', 'contact_1'=>'(81) 3101-0315', 'contact_2'=>'0315', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coordenação de Nutrição', 'contact_1'=>'(81) 3101-0316', 'contact_2'=>'0316', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Posto de Enfermagem I', 'contact_1'=>'(81) 3101-0317', 'contact_2'=>'0317', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Sala de Admissão', 'contact_1'=>'(81) 3101-0318', 'contact_2'=>'0318', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coordenação de Enfermagem', 'contact_1'=>'(81) 3101-0319', 'contact_2'=>'0319', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'SAME', 'contact_1'=>'(81) 3101-0320', 'contact_2'=>'0320', 'type'=>'Interno', 'establishment_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0371', 'contact_2'=>'0371', 'type'=>'Principal', 'establishment_id'=>30,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0372', 'contact_2'=>'0372', 'type'=>'Principal', 'establishment_id'=>29,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção Obstetra', 'contact_1'=>'(81) 3101-0326', 'contact_2'=>'0326', 'type'=>'Principal', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção Ambulatório', 'contact_1'=>'(81) 3101-0327', 'contact_2'=>'0327', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Almoxarifado', 'contact_1'=>'(81) 3101-0328', 'contact_2'=>'0328', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Rouparia', 'contact_1'=>'(81) 3101-0329', 'contact_2'=>'0329', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Repouso Médico (Feminino)', 'contact_1'=>'(81) 3101-0330', 'contact_2'=>'0330', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Repouso Médico (Masculino)', 'contact_1'=>'(81) 3101-0331', 'contact_2'=>'0331', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'PPP', 'contact_1'=>'(81) 3101-0332', 'contact_2'=>'0332', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Nutrição', 'contact_1'=>'(81) 3101-0333', 'contact_2'=>'0333', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0334', 'contact_2'=>'0334', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CME', 'contact_1'=>'(81) 3101-0335', 'contact_2'=>'0335', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Clínica Cirurgica', 'contact_1'=>'(81) 3101-0336', 'contact_2'=>'0336', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Classificação de Risco', 'contact_1'=>'(81) 3101-0337', 'contact_2'=>'0337', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Bloco Cirurgico', 'contact_1'=>'(81) 3101-0338', 'contact_2'=>'0338', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gerência', 'contact_1'=>'(81) 3101-0339', 'contact_2'=>'0339', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Alojamento Conjunto', 'contact_1'=>'(81) 3101-0340', 'contact_2'=>'0340', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Serviço Social', 'contact_1'=>'(81) 3101-0341', 'contact_2'=>'0341', 'type'=>'Interno', 'establishment_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'TFD', 'contact_1'=>'(81) 3101-0346', 'contact_2'=>'0346', 'type'=>'Principal', 'establishment_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Controle', 'contact_1'=>'(81) 3101-0347', 'contact_2'=>'0347', 'type'=>'Interno', 'establishment_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Alta Complexidade', 'contact_1'=>'(81) 3101-0348', 'contact_2'=>'0348', 'type'=>'Interno', 'establishment_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Programação', 'contact_1'=>'(81) 3101-0349', 'contact_2'=>'0349', 'type'=>'Interno', 'establishment_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Callcenter', 'contact_1'=>'(81) 3101-0350', 'contact_2'=>'0350', 'type'=>'Interno', 'establishment_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Nutrição', 'contact_1'=>'(81) 3101-0249', 'contact_2'=>'0249', 'type'=>'Interno', 'establishment_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Tecnologia da Informação e Comunicação', 'contact_1'=>'(81) 3101-0250', 'contact_2'=>'0250', 'type'=>'Interno', 'establishment_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0251', 'contact_2'=>'0251', 'type'=>'Interno', 'establishment_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coordenação de Enfermagem', 'contact_1'=>'(81) 3101-0252', 'contact_2'=>'0252', 'type'=>'Interno', 'establishment_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0254', 'contact_2'=>'0254', 'type'=>'Interno', 'establishment_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0248', 'contact_2'=>'0248', 'type'=>'Interno', 'establishment_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0201', 'contact_2'=>'0201', 'type'=>'Principal', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Manutenção', 'contact_1'=>'(81) 3101-0245', 'contact_2'=>'0245', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Engenharia', 'contact_1'=>'(81) 3101-0246', 'contact_2'=>'0246', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Tecnoligia da Informação e Comunicação', 'contact_1'=>'(81) 3101-0230', 'contact_2'=>'0230', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Engenharia', 'contact_1'=>'(81) 3101-0231', 'contact_2'=>'0231', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Almoxarifado', 'contact_1'=>'(81) 3101-0222', 'contact_2'=>'0222', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recurso Humano', 'contact_1'=>'(81) 3101-0255', 'contact_2'=>'0255', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0202', 'contact_2'=>'0202', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Transporte', 'contact_1'=>'(81) 3101-0203', 'contact_2'=>'0203', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Nutrição', 'contact_1'=>'(81) 3101-0204', 'contact_2'=>'0204', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Ouvidoria', 'contact_1'=>'(81) 3101-0205', 'contact_2'=>'0205', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'PNI', 'contact_1'=>'(81) 3101-0206', 'contact_2'=>'0206', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Recepção', 'contact_1'=>'(81) 3101-0207', 'contact_2'=>'0207', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Gerência', 'contact_1'=>'(81) 3101-0208', 'contact_2'=>'0208', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Coordenação', 'contact_1'=>'(81) 3101-0209', 'contact_2'=>'0209', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Farmácia', 'contact_1'=>'(81) 3101-0210', 'contact_2'=>'0210', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Odonto', 'contact_1'=>'(81) 3101-0211', 'contact_2'=>'0211', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Estoque Medicamentos', 'contact_1'=>'(81) 3101-0212', 'contact_2'=>'0212', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Estoque Material', 'contact_1'=>'(81) 3101-0213', 'contact_2'=>'0213', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CAF - Remédio na Porta', 'contact_1'=>'(81) 3101-0214', 'contact_2'=>'0214', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Vigiância Sanitária', 'contact_1'=>'(81) 3101-0215', 'contact_2'=>'0215', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Vigilância Ambiental', 'contact_1'=>'(81) 3101-0216', 'contact_2'=>'0216', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Vigilância Recepção', 'contact_1'=>'(81) 3101-0217', 'contact_2'=>'0217', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Vigilância Recurso Humano', 'contact_1'=>'(81) 3101-0218', 'contact_2'=>'0218', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gabinete Recepção', 'contact_1'=>'(81) 3101-0219', 'contact_2'=>'0219', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gabinete', 'contact_1'=>'(81) 3101-0220', 'contact_2'=>'0220', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Atenção Especializada - Secretário Execultivo', 'contact_1'=>'(81) 3101-0221', 'contact_2'=>'0221', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Atenção Especializada - Cirurgias', 'contact_1'=>'(81) 3101-0223', 'contact_2'=>'0223', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Atenção Especializada - Recepção', 'contact_1'=>'(81) 3101-0224', 'contact_2'=>'0224', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0225', 'contact_2'=>'0225', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Compras', 'contact_1'=>'(81) 3101-0226', 'contact_2'=>'0226', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Análise de Processos', 'contact_1'=>'(81) 3101-0227', 'contact_2'=>'0227', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gestão de Contratos', 'contact_1'=>'(81) 3101-0227', 'contact_2'=>'0227', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Fundo Municipal de Saúde', 'contact_1'=>'(81) 3101-0228', 'contact_2'=>'0228', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gerência Geral', 'contact_1'=>'(81) 3101-0229', 'contact_2'=>'0229', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Auditoria', 'contact_1'=>'(81) 3101-0236', 'contact_2'=>'0236', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CPL', 'contact_1'=>'(81) 3101-0237', 'contact_2'=>'0237', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CPL', 'contact_1'=>'(81) 3101-0238', 'contact_2'=>'0238', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'CPL', 'contact_1'=>'(81) 3101-0239', 'contact_2'=>'0239', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Atenção Básico - Recepção', 'contact_1'=>'(81) 3101-0240', 'contact_2'=>'0240', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Conselho Municipal', 'contact_1'=>'(81) 3101-0243', 'contact_2'=>'0243', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Portaria', 'contact_1'=>'(81) 3101-0244', 'contact_2'=>'0244', 'type'=>'Interno', 'establishment_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0422', 'contact_2'=>'0422', 'type'=>'Principal', 'establishment_id'=>32,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0402', 'contact_2'=>'0402', 'type'=>'Principal', 'establishment_id'=>33,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0410', 'contact_2'=>'0410', 'type'=>'Principal', 'establishment_id'=>34,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0429', 'contact_2'=>'0429', 'type'=>'Principal', 'establishment_id'=>35,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0414', 'contact_2'=>'0414', 'type'=>'Principal', 'establishment_id'=>36,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0357', 'contact_2'=>'0357', 'type'=>'Principal', 'establishment_id'=>37,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0393', 'contact_2'=>'0393', 'type'=>'Principal', 'establishment_id'=>38,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0415', 'contact_2'=>'0415', 'type'=>'Principal', 'establishment_id'=>39,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0413', 'contact_2'=>'0413', 'type'=>'Principal', 'establishment_id'=>40,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0408', 'contact_2'=>'0408', 'type'=>'Principal', 'establishment_id'=>41,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0365', 'contact_2'=>'0365', 'type'=>'Principal', 'establishment_id'=>42,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0396', 'contact_2'=>'0396', 'type'=>'Principal', 'establishment_id'=>43,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0427', 'contact_2'=>'0427', 'type'=>'Principal', 'establishment_id'=>44,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0267', 'contact_2'=>'0267', 'type'=>'Principal', 'establishment_id'=>45,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0407', 'contact_2'=>'0407', 'type'=>'Principal', 'establishment_id'=>46,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0401', 'contact_2'=>'0401', 'type'=>'Principal', 'establishment_id'=>47,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0399', 'contact_2'=>'0399', 'type'=>'Principal', 'establishment_id'=>48,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0272', 'contact_2'=>'0272', 'type'=>'Principal', 'establishment_id'=>49,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0386', 'contact_2'=>'0386', 'type'=>'Principal', 'establishment_id'=>50,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0412', 'contact_2'=>'0412', 'type'=>'Principal', 'establishment_id'=>51,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0428', 'contact_2'=>'0428', 'type'=>'Principal', 'establishment_id'=>52,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0268', 'contact_2'=>'0268', 'type'=>'Principal', 'establishment_id'=>53,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0275', 'contact_2'=>'0275', 'type'=>'Principal', 'establishment_id'=>54,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0420', 'contact_2'=>'0420', 'type'=>'Principal', 'establishment_id'=>55,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0323', 'contact_2'=>'0323', 'type'=>'Principal', 'establishment_id'=>56,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0404', 'contact_2'=>'0404', 'type'=>'Principal', 'establishment_id'=>57,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0419', 'contact_2'=>'0419', 'type'=>'Principal', 'establishment_id'=>58,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0377', 'contact_2'=>'0377', 'type'=>'Principal', 'establishment_id'=>59,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0392', 'contact_2'=>'0392', 'type'=>'Principal', 'establishment_id'=>60,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0392', 'contact_2'=>'0392', 'type'=>'Principal', 'establishment_id'=>61,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0426', 'contact_2'=>'0426', 'type'=>'Principal', 'establishment_id'=>62,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0387', 'contact_2'=>'0387', 'type'=>'Principal', 'establishment_id'=>63,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0389', 'contact_2'=>'0389', 'type'=>'Principal', 'establishment_id'=>64,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0271', 'contact_2'=>'0271', 'type'=>'Principal', 'establishment_id'=>65,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0411', 'contact_2'=>'0411', 'type'=>'Principal', 'establishment_id'=>66,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0416', 'contact_2'=>'0416', 'type'=>'Principal', 'establishment_id'=>67,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0273', 'contact_2'=>'0273', 'type'=>'Principal', 'establishment_id'=>68,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0421', 'contact_2'=>'0421', 'type'=>'Principal', 'establishment_id'=>69,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0406', 'contact_2'=>'0406', 'type'=>'Principal', 'establishment_id'=>70,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0270', 'contact_2'=>'0270', 'type'=>'Principal', 'establishment_id'=>8,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0395', 'contact_2'=>'0395', 'type'=>'Principal', 'establishment_id'=>71,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0430', 'contact_2'=>'0430', 'type'=>'Principal', 'establishment_id'=>72,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0394', 'contact_2'=>'0394', 'type'=>'Principal', 'establishment_id'=>73,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0400', 'contact_2'=>'0400', 'type'=>'Principal', 'establishment_id'=>74,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0423', 'contact_2'=>'0423', 'type'=>'Principal', 'establishment_id'=>75,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0388', 'contact_2'=>'0388', 'type'=>'Principal', 'establishment_id'=>76,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0324', 'contact_2'=>'0324', 'type'=>'Principal', 'establishment_id'=>77,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0397', 'contact_2'=>'0397', 'type'=>'Principal', 'establishment_id'=>78,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0391', 'contact_2'=>'0391', 'type'=>'Principal', 'establishment_id'=>79,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0269', 'contact_2'=>'0269', 'type'=>'Principal', 'establishment_id'=>80,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0418', 'contact_2'=>'0418', 'type'=>'Principal', 'establishment_id'=>81,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0425', 'contact_2'=>'0425', 'type'=>'Principal', 'establishment_id'=>82,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0393', 'contact_2'=>'0393', 'type'=>'Principal', 'establishment_id'=>83,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0424', 'contact_2'=>'0424', 'type'=>'Principal', 'establishment_id'=>84,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0398', 'contact_2'=>'0398', 'type'=>'Principal', 'establishment_id'=>85,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0256', 'contact_2'=>'0256', 'type'=>'Principal', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0257', 'contact_2'=>'0257', 'type'=>'Interno', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coordenação de Enfermagem', 'contact_1'=>'(81) 3101-0258', 'contact_2'=>'0258', 'type'=>'Interno', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Serviço Social', 'contact_1'=>'(81) 3101-0259', 'contact_2'=>'0259', 'type'=>'Interno', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0260', 'contact_2'=>'0260', 'type'=>'Interno', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Gerência', 'contact_1'=>'(81) 3101-0261', 'contact_2'=>'0261', 'type'=>'Interno', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Sala Vermelha', 'contact_1'=>'(81) 3101-0262', 'contact_2'=>'0262', 'type'=>'Interno', 'establishment_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0276', 'contact_2'=>'0276', 'type'=>'Principal', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0277', 'contact_2'=>'0276', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'SAME', 'contact_1'=>'(81) 3101-0278', 'contact_2'=>'0278', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Classificação de Risco', 'contact_1'=>'(81) 3101-0279', 'contact_2'=>'0279', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Pediatria', 'contact_1'=>'(81) 3101-0280', 'contact_2'=>'0280', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Copa', 'contact_1'=>'(81) 3101-0281', 'contact_2'=>'0281', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Serviço Social', 'contact_1'=>'(81) 3101-0282', 'contact_2'=>'0282', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0283', 'contact_2'=>'0283', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Sala Verde', 'contact_1'=>'(81) 3101-0284', 'contact_2'=>'0284', 'type'=>'Interno', 'establishment_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0286', 'contact_2'=>'0286', 'type'=>'Principal', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Farmácia', 'contact_1'=>'(81) 3101-0287', 'contact_2'=>'0287', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Serviço Social', 'contact_1'=>'(81) 3101-0288', 'contact_2'=>'0288', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coleta', 'contact_1'=>'(81) 3101-0289', 'contact_2'=>'0289', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Coordenação de Enfermagem', 'contact_1'=>'(81) 3101-0290', 'contact_2'=>'0290', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Administração', 'contact_1'=>'(81) 3101-0291', 'contact_2'=>'0291', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Nutrição', 'contact_1'=>'(81) 3101-0292', 'contact_2'=>'0292', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'SAME', 'contact_1'=>'(81) 3101-0293', 'contact_2'=>'0293', 'type'=>'Interno', 'establishment_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0370', 'contact_2'=>'0370', 'type'=>'Principal', 'establishment_id'=>88,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0362', 'contact_2'=>'0362', 'type'=>'Principal', 'establishment_id'=>89,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Infocras', 'contact_1'=>'(81) 3101-0363', 'contact_2'=>'0363', 'type'=>'Interno', 'establishment_id'=>89,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0403', 'contact_2'=>'0403', 'type'=>'Principal', 'establishment_id'=>90,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0364', 'contact_2'=>'0364', 'type'=>'Principal', 'establishment_id'=>96,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recepção', 'contact_1'=>'(81) 3101-0217', 'contact_2'=>'0217', 'type'=>'Interno', 'establishment_id'=>87,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Vigilância Ambiental', 'contact_1'=>'(81) 3101-0216', 'contact_2'=>'0216', 'type'=>'Interno', 'establishment_id'=>87,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Vigilância Sanitária', 'contact_1'=>'(81) 3101-0215', 'contact_2'=>'0215', 'type'=>'Interno', 'establishment_id'=>87,]);
        CompanyEstablishmentContactsModel::create([ 'department'=>'Recursos Humanos', 'contact_1'=>'(81) 3101-0218', 'contact_2'=>'0218', 'type'=>'Interno', 'establishment_id'=>87,]);
    }
}
