<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\CompanyEstablishmentContactsModel;

class CompanyEstablishmentContactsSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0351', 'con_unidade_2'=>'0351', 'con_principal'=>'Principal', 'estabelecimento_id'=>1,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0352', 'con_unidade_2'=>'0352', 'con_principal'=>'Interno', 'estabelecimento_id'=>1,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Infocras', 'con_unidade'=>'(81) 3101-0353', 'con_unidade_2'=>'0353', 'con_principal'=>'Interno', 'estabelecimento_id'=>1,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Sala de Exames', 'con_unidade'=>'(81) 3101-0356', 'con_unidade_2'=>'0356', 'con_principal'=>'Principal', 'estabelecimento_id'=>2,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0405', 'con_unidade_2'=>'0405', 'con_principal'=>'Principal', 'estabelecimento_id'=>3,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0354', 'con_unidade_2'=>'0354', 'con_principal'=>'Principal', 'estabelecimento_id'=>4,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0355', 'con_unidade_2'=>'0355', 'con_principal'=>'Interno', 'estabelecimento_id'=>4,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0409', 'con_unidade_2'=>'0409', 'con_principal'=>'Principal', 'estabelecimento_id'=>5,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0274', 'con_unidade_2'=>'0274', 'con_principal'=>'Principal', 'estabelecimento_id'=>6,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0390', 'con_unidade_2'=>'0390', 'con_principal'=>'Principal', 'estabelecimento_id'=>7,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0360', 'con_unidade_2'=>'0360', 'con_principal'=>'Principal', 'estabelecimento_id'=>9,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0361', 'con_unidade_2'=>'0361', 'con_principal'=>'Interno', 'estabelecimento_id'=>9,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0366', 'con_unidade_2'=>'0366', 'con_principal'=>'Principal', 'estabelecimento_id'=>10,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0367', 'con_unidade_2'=>'0367', 'con_principal'=>'Interno', 'estabelecimento_id'=>10,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0207', 'con_unidade_2'=>'0207', 'con_principal'=>'Principal', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gerência', 'con_unidade'=>'(81) 3101-0208', 'con_unidade_2'=>'0208', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coordenação', 'con_unidade'=>'(81) 3101-0209', 'con_unidade_2'=>'0209', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0210', 'con_unidade_2'=>'0210', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Odonto', 'con_unidade'=>'(81) 3101-0211', 'con_unidade_2'=>'0211', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Estoque Medicamentos', 'con_unidade'=>'(81) 3101-0212', 'con_unidade_2'=>'0212', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Estoque Material', 'con_unidade'=>'(81) 3101-0213', 'con_unidade_2'=>'0213', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Remédio na Porta', 'con_unidade'=>'(81) 3101-0214', 'con_unidade_2'=>'0214', 'con_principal'=>'Interno', 'estabelecimento_id'=>13,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0368', 'con_unidade_2'=>'0368', 'con_principal'=>'Principal', 'estabelecimento_id'=>11,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0369', 'con_unidade_2'=>'0369', 'con_principal'=>'Principal', 'estabelecimento_id'=>12,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0375', 'con_unidade_2'=>'0375', 'con_principal'=>'Principal', 'estabelecimento_id'=>23,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0374', 'con_unidade_2'=>'0374', 'con_principal'=>'Principal', 'estabelecimento_id'=>15,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0373', 'con_unidade_2'=>'0373', 'con_principal'=>'Principal', 'estabelecimento_id'=>24,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0384', 'con_unidade_2'=>'0384', 'con_principal'=>'Principal', 'estabelecimento_id'=>16,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0382', 'con_unidade_2'=>'0382', 'con_principal'=>'Principal', 'estabelecimento_id'=>17,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0378', 'con_unidade_2'=>'0378', 'con_principal'=>'Principal', 'estabelecimento_id'=>18,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0379', 'con_unidade_2'=>'0379', 'con_principal'=>'Interno', 'estabelecimento_id'=>18,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0380', 'con_unidade_2'=>'0380', 'con_principal'=>'Principal', 'estabelecimento_id'=>19,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0358', 'con_unidade_2'=>'0358', 'con_principal'=>'Principal', 'estabelecimento_id'=>20,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0359', 'con_unidade_2'=>'0359', 'con_principal'=>'Interno', 'estabelecimento_id'=>20,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0417', 'con_unidade_2'=>'0417', 'con_principal'=>'Principal', 'estabelecimento_id'=>21,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gerência', 'con_unidade'=>'(81) 3101-0235', 'con_unidade_2'=>'0235', 'con_principal'=>'Interno', 'estabelecimento_id'=>98,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0345', 'con_unidade_2'=>'0345', 'con_principal'=>'Principal', 'estabelecimento_id'=>25,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0376', 'con_unidade_2'=>'0376', 'con_principal'=>'Principal', 'estabelecimento_id'=>26,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0210', 'con_unidade_2'=>'0210', 'con_principal'=>'Interno', 'estabelecimento_id'=>27,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0306', 'con_unidade_2'=>'0306', 'con_principal'=>'Principal', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gerência', 'con_unidade'=>'(81) 3101-0307', 'con_unidade_2'=>'0307', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0308', 'con_unidade_2'=>'0308', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Posto de Enfermagem II', 'con_unidade'=>'(81) 3101-0309', 'con_unidade_2'=>'0309', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Laboratório', 'con_unidade'=>'(81) 3101-0310', 'con_unidade_2'=>'0310', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Serviço Social', 'con_unidade'=>'(81) 3101-0311', 'con_unidade_2'=>'0311', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Nutrição', 'con_unidade'=>'(81) 3101-0312', 'con_unidade_2'=>'0312', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0313', 'con_unidade_2'=>'0313', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CCIH', 'con_unidade'=>'(81) 3101-0314', 'con_unidade_2'=>'0314', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Pediatria', 'con_unidade'=>'(81) 3101-0315', 'con_unidade_2'=>'0315', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coordenação de Nutrição', 'con_unidade'=>'(81) 3101-0316', 'con_unidade_2'=>'0316', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Posto de Enfermagem I', 'con_unidade'=>'(81) 3101-0317', 'con_unidade_2'=>'0317', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Sala de Admissão', 'con_unidade'=>'(81) 3101-0318', 'con_unidade_2'=>'0318', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coordenação de Enfermagem', 'con_unidade'=>'(81) 3101-0319', 'con_unidade_2'=>'0319', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'SAME', 'con_unidade'=>'(81) 3101-0320', 'con_unidade_2'=>'0320', 'con_principal'=>'Interno', 'estabelecimento_id'=>28,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0371', 'con_unidade_2'=>'0371', 'con_principal'=>'Principal', 'estabelecimento_id'=>30,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0372', 'con_unidade_2'=>'0372', 'con_principal'=>'Principal', 'estabelecimento_id'=>29,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção Obstetra', 'con_unidade'=>'(81) 3101-0326', 'con_unidade_2'=>'0326', 'con_principal'=>'Principal', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção Ambulatório', 'con_unidade'=>'(81) 3101-0327', 'con_unidade_2'=>'0327', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Almoxarifado', 'con_unidade'=>'(81) 3101-0328', 'con_unidade_2'=>'0328', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Rouparia', 'con_unidade'=>'(81) 3101-0329', 'con_unidade_2'=>'0329', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Repouso Médico (Feminino)', 'con_unidade'=>'(81) 3101-0330', 'con_unidade_2'=>'0330', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Repouso Médico (Masculino)', 'con_unidade'=>'(81) 3101-0331', 'con_unidade_2'=>'0331', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'PPP', 'con_unidade'=>'(81) 3101-0332', 'con_unidade_2'=>'0332', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Nutrição', 'con_unidade'=>'(81) 3101-0333', 'con_unidade_2'=>'0333', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0334', 'con_unidade_2'=>'0334', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CME', 'con_unidade'=>'(81) 3101-0335', 'con_unidade_2'=>'0335', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Clínica Cirurgica', 'con_unidade'=>'(81) 3101-0336', 'con_unidade_2'=>'0336', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Classificação de Risco', 'con_unidade'=>'(81) 3101-0337', 'con_unidade_2'=>'0337', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Bloco Cirurgico', 'con_unidade'=>'(81) 3101-0338', 'con_unidade_2'=>'0338', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gerência', 'con_unidade'=>'(81) 3101-0339', 'con_unidade_2'=>'0339', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Alojamento Conjunto', 'con_unidade'=>'(81) 3101-0340', 'con_unidade_2'=>'0340', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Serviço Social', 'con_unidade'=>'(81) 3101-0341', 'con_unidade_2'=>'0341', 'con_principal'=>'Interno', 'estabelecimento_id'=>31,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'TFD', 'con_unidade'=>'(81) 3101-0346', 'con_unidade_2'=>'0346', 'con_principal'=>'Principal', 'estabelecimento_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Controle', 'con_unidade'=>'(81) 3101-0347', 'con_unidade_2'=>'0347', 'con_principal'=>'Interno', 'estabelecimento_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Alta Complexidade', 'con_unidade'=>'(81) 3101-0348', 'con_unidade_2'=>'0348', 'con_principal'=>'Interno', 'estabelecimento_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Programação', 'con_unidade'=>'(81) 3101-0349', 'con_unidade_2'=>'0349', 'con_principal'=>'Interno', 'estabelecimento_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Callcenter', 'con_unidade'=>'(81) 3101-0350', 'con_unidade_2'=>'0350', 'con_principal'=>'Interno', 'estabelecimento_id'=>14,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Nutrição', 'con_unidade'=>'(81) 3101-0249', 'con_unidade_2'=>'0249', 'con_principal'=>'Interno', 'estabelecimento_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Tecnologia da Informação e Comunicação', 'con_unidade'=>'(81) 3101-0250', 'con_unidade_2'=>'0250', 'con_principal'=>'Interno', 'estabelecimento_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0251', 'con_unidade_2'=>'0251', 'con_principal'=>'Interno', 'estabelecimento_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coordenação de Enfermagem', 'con_unidade'=>'(81) 3101-0252', 'con_unidade_2'=>'0252', 'con_principal'=>'Interno', 'estabelecimento_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0254', 'con_unidade_2'=>'0254', 'con_principal'=>'Interno', 'estabelecimento_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0248', 'con_unidade_2'=>'0248', 'con_principal'=>'Interno', 'estabelecimento_id'=>97,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0201', 'con_unidade_2'=>'0201', 'con_principal'=>'Principal', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Manutenção', 'con_unidade'=>'(81) 3101-0245', 'con_unidade_2'=>'0245', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Engenharia', 'con_unidade'=>'(81) 3101-0246', 'con_unidade_2'=>'0246', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Tecnoligia da Informação e Comunicação', 'con_unidade'=>'(81) 3101-0230', 'con_unidade_2'=>'0230', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Engenharia', 'con_unidade'=>'(81) 3101-0231', 'con_unidade_2'=>'0231', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Almoxarifado', 'con_unidade'=>'(81) 3101-0222', 'con_unidade_2'=>'0222', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recurso Humano', 'con_unidade'=>'(81) 3101-0255', 'con_unidade_2'=>'0255', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0202', 'con_unidade_2'=>'0202', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Transporte', 'con_unidade'=>'(81) 3101-0203', 'con_unidade_2'=>'0203', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Nutrição', 'con_unidade'=>'(81) 3101-0204', 'con_unidade_2'=>'0204', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Ouvidoria', 'con_unidade'=>'(81) 3101-0205', 'con_unidade_2'=>'0205', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'PNI', 'con_unidade'=>'(81) 3101-0206', 'con_unidade_2'=>'0206', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Recepção', 'con_unidade'=>'(81) 3101-0207', 'con_unidade_2'=>'0207', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Gerência', 'con_unidade'=>'(81) 3101-0208', 'con_unidade_2'=>'0208', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Coordenação', 'con_unidade'=>'(81) 3101-0209', 'con_unidade_2'=>'0209', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Farmácia', 'con_unidade'=>'(81) 3101-0210', 'con_unidade_2'=>'0210', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Odonto', 'con_unidade'=>'(81) 3101-0211', 'con_unidade_2'=>'0211', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Estoque Medicamentos', 'con_unidade'=>'(81) 3101-0212', 'con_unidade_2'=>'0212', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Estoque Material', 'con_unidade'=>'(81) 3101-0213', 'con_unidade_2'=>'0213', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CAF - Remédio na Porta', 'con_unidade'=>'(81) 3101-0214', 'con_unidade_2'=>'0214', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Vigiância Sanitária', 'con_unidade'=>'(81) 3101-0215', 'con_unidade_2'=>'0215', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Vigilância Ambiental', 'con_unidade'=>'(81) 3101-0216', 'con_unidade_2'=>'0216', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Vigilância Recepção', 'con_unidade'=>'(81) 3101-0217', 'con_unidade_2'=>'0217', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Vigilância Recurso Humano', 'con_unidade'=>'(81) 3101-0218', 'con_unidade_2'=>'0218', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gabinete Recepção', 'con_unidade'=>'(81) 3101-0219', 'con_unidade_2'=>'0219', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gabinete', 'con_unidade'=>'(81) 3101-0220', 'con_unidade_2'=>'0220', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Atenção Especializada - Secretário Execultivo', 'con_unidade'=>'(81) 3101-0221', 'con_unidade_2'=>'0221', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Atenção Especializada - Cirurgias', 'con_unidade'=>'(81) 3101-0223', 'con_unidade_2'=>'0223', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Atenção Especializada - Recepção', 'con_unidade'=>'(81) 3101-0224', 'con_unidade_2'=>'0224', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0225', 'con_unidade_2'=>'0225', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Compras', 'con_unidade'=>'(81) 3101-0226', 'con_unidade_2'=>'0226', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Análise de Processos', 'con_unidade'=>'(81) 3101-0227', 'con_unidade_2'=>'0227', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gestão de Contratos', 'con_unidade'=>'(81) 3101-0227', 'con_unidade_2'=>'0227', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Fundo Municipal de Saúde', 'con_unidade'=>'(81) 3101-0228', 'con_unidade_2'=>'0228', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gerência Geral', 'con_unidade'=>'(81) 3101-0229', 'con_unidade_2'=>'0229', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Auditoria', 'con_unidade'=>'(81) 3101-0236', 'con_unidade_2'=>'0236', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CPL', 'con_unidade'=>'(81) 3101-0237', 'con_unidade_2'=>'0237', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CPL', 'con_unidade'=>'(81) 3101-0238', 'con_unidade_2'=>'0238', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'CPL', 'con_unidade'=>'(81) 3101-0239', 'con_unidade_2'=>'0239', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Atenção Básico - Recepção', 'con_unidade'=>'(81) 3101-0240', 'con_unidade_2'=>'0240', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Conselho Municipal', 'con_unidade'=>'(81) 3101-0243', 'con_unidade_2'=>'0243', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Portaria', 'con_unidade'=>'(81) 3101-0244', 'con_unidade_2'=>'0244', 'con_principal'=>'Interno', 'estabelecimento_id'=>94,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0422', 'con_unidade_2'=>'0422', 'con_principal'=>'Principal', 'estabelecimento_id'=>32,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0402', 'con_unidade_2'=>'0402', 'con_principal'=>'Principal', 'estabelecimento_id'=>33,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0410', 'con_unidade_2'=>'0410', 'con_principal'=>'Principal', 'estabelecimento_id'=>34,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0429', 'con_unidade_2'=>'0429', 'con_principal'=>'Principal', 'estabelecimento_id'=>35,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0414', 'con_unidade_2'=>'0414', 'con_principal'=>'Principal', 'estabelecimento_id'=>36,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0357', 'con_unidade_2'=>'0357', 'con_principal'=>'Principal', 'estabelecimento_id'=>37,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0393', 'con_unidade_2'=>'0393', 'con_principal'=>'Principal', 'estabelecimento_id'=>38,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0415', 'con_unidade_2'=>'0415', 'con_principal'=>'Principal', 'estabelecimento_id'=>39,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0413', 'con_unidade_2'=>'0413', 'con_principal'=>'Principal', 'estabelecimento_id'=>40,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0408', 'con_unidade_2'=>'0408', 'con_principal'=>'Principal', 'estabelecimento_id'=>41,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0365', 'con_unidade_2'=>'0365', 'con_principal'=>'Principal', 'estabelecimento_id'=>42,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0396', 'con_unidade_2'=>'0396', 'con_principal'=>'Principal', 'estabelecimento_id'=>43,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0427', 'con_unidade_2'=>'0427', 'con_principal'=>'Principal', 'estabelecimento_id'=>44,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0267', 'con_unidade_2'=>'0267', 'con_principal'=>'Principal', 'estabelecimento_id'=>45,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0407', 'con_unidade_2'=>'0407', 'con_principal'=>'Principal', 'estabelecimento_id'=>46,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0401', 'con_unidade_2'=>'0401', 'con_principal'=>'Principal', 'estabelecimento_id'=>47,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0399', 'con_unidade_2'=>'0399', 'con_principal'=>'Principal', 'estabelecimento_id'=>48,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0272', 'con_unidade_2'=>'0272', 'con_principal'=>'Principal', 'estabelecimento_id'=>49,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0386', 'con_unidade_2'=>'0386', 'con_principal'=>'Principal', 'estabelecimento_id'=>50,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0412', 'con_unidade_2'=>'0412', 'con_principal'=>'Principal', 'estabelecimento_id'=>51,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0428', 'con_unidade_2'=>'0428', 'con_principal'=>'Principal', 'estabelecimento_id'=>52,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0268', 'con_unidade_2'=>'0268', 'con_principal'=>'Principal', 'estabelecimento_id'=>53,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0275', 'con_unidade_2'=>'0275', 'con_principal'=>'Principal', 'estabelecimento_id'=>54,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0420', 'con_unidade_2'=>'0420', 'con_principal'=>'Principal', 'estabelecimento_id'=>55,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0323', 'con_unidade_2'=>'0323', 'con_principal'=>'Principal', 'estabelecimento_id'=>56,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0404', 'con_unidade_2'=>'0404', 'con_principal'=>'Principal', 'estabelecimento_id'=>57,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0419', 'con_unidade_2'=>'0419', 'con_principal'=>'Principal', 'estabelecimento_id'=>58,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0377', 'con_unidade_2'=>'0377', 'con_principal'=>'Principal', 'estabelecimento_id'=>59,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0392', 'con_unidade_2'=>'0392', 'con_principal'=>'Principal', 'estabelecimento_id'=>60,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0392', 'con_unidade_2'=>'0392', 'con_principal'=>'Principal', 'estabelecimento_id'=>61,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0426', 'con_unidade_2'=>'0426', 'con_principal'=>'Principal', 'estabelecimento_id'=>62,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0387', 'con_unidade_2'=>'0387', 'con_principal'=>'Principal', 'estabelecimento_id'=>63,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0389', 'con_unidade_2'=>'0389', 'con_principal'=>'Principal', 'estabelecimento_id'=>64,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0271', 'con_unidade_2'=>'0271', 'con_principal'=>'Principal', 'estabelecimento_id'=>65,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0411', 'con_unidade_2'=>'0411', 'con_principal'=>'Principal', 'estabelecimento_id'=>66,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0416', 'con_unidade_2'=>'0416', 'con_principal'=>'Principal', 'estabelecimento_id'=>67,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0273', 'con_unidade_2'=>'0273', 'con_principal'=>'Principal', 'estabelecimento_id'=>68,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0421', 'con_unidade_2'=>'0421', 'con_principal'=>'Principal', 'estabelecimento_id'=>69,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0406', 'con_unidade_2'=>'0406', 'con_principal'=>'Principal', 'estabelecimento_id'=>70,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0270', 'con_unidade_2'=>'0270', 'con_principal'=>'Principal', 'estabelecimento_id'=>8,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0395', 'con_unidade_2'=>'0395', 'con_principal'=>'Principal', 'estabelecimento_id'=>71,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0430', 'con_unidade_2'=>'0430', 'con_principal'=>'Principal', 'estabelecimento_id'=>72,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0394', 'con_unidade_2'=>'0394', 'con_principal'=>'Principal', 'estabelecimento_id'=>73,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0400', 'con_unidade_2'=>'0400', 'con_principal'=>'Principal', 'estabelecimento_id'=>74,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0423', 'con_unidade_2'=>'0423', 'con_principal'=>'Principal', 'estabelecimento_id'=>75,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0388', 'con_unidade_2'=>'0388', 'con_principal'=>'Principal', 'estabelecimento_id'=>76,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0324', 'con_unidade_2'=>'0324', 'con_principal'=>'Principal', 'estabelecimento_id'=>77,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0397', 'con_unidade_2'=>'0397', 'con_principal'=>'Principal', 'estabelecimento_id'=>78,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0391', 'con_unidade_2'=>'0391', 'con_principal'=>'Principal', 'estabelecimento_id'=>79,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0269', 'con_unidade_2'=>'0269', 'con_principal'=>'Principal', 'estabelecimento_id'=>80,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0418', 'con_unidade_2'=>'0418', 'con_principal'=>'Principal', 'estabelecimento_id'=>81,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0425', 'con_unidade_2'=>'0425', 'con_principal'=>'Principal', 'estabelecimento_id'=>82,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0393', 'con_unidade_2'=>'0393', 'con_principal'=>'Principal', 'estabelecimento_id'=>83,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0424', 'con_unidade_2'=>'0424', 'con_principal'=>'Principal', 'estabelecimento_id'=>84,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0398', 'con_unidade_2'=>'0398', 'con_principal'=>'Principal', 'estabelecimento_id'=>85,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0256', 'con_unidade_2'=>'0256', 'con_principal'=>'Principal', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0257', 'con_unidade_2'=>'0257', 'con_principal'=>'Interno', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coordenação de Enfermagem', 'con_unidade'=>'(81) 3101-0258', 'con_unidade_2'=>'0258', 'con_principal'=>'Interno', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Serviço Social', 'con_unidade'=>'(81) 3101-0259', 'con_unidade_2'=>'0259', 'con_principal'=>'Interno', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0260', 'con_unidade_2'=>'0260', 'con_principal'=>'Interno', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Gerência', 'con_unidade'=>'(81) 3101-0261', 'con_unidade_2'=>'0261', 'con_principal'=>'Interno', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Sala Vermelha', 'con_unidade'=>'(81) 3101-0262', 'con_unidade_2'=>'0262', 'con_principal'=>'Interno', 'estabelecimento_id'=>91,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0276', 'con_unidade_2'=>'0276', 'con_principal'=>'Principal', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0277', 'con_unidade_2'=>'0276', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'SAME', 'con_unidade'=>'(81) 3101-0278', 'con_unidade_2'=>'0278', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Classificação de Risco', 'con_unidade'=>'(81) 3101-0279', 'con_unidade_2'=>'0279', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Pediatria', 'con_unidade'=>'(81) 3101-0280', 'con_unidade_2'=>'0280', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Copa', 'con_unidade'=>'(81) 3101-0281', 'con_unidade_2'=>'0281', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Serviço Social', 'con_unidade'=>'(81) 3101-0282', 'con_unidade_2'=>'0282', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0283', 'con_unidade_2'=>'0283', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Sala Verde', 'con_unidade'=>'(81) 3101-0284', 'con_unidade_2'=>'0284', 'con_principal'=>'Interno', 'estabelecimento_id'=>93,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0286', 'con_unidade_2'=>'0286', 'con_principal'=>'Principal', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Farmácia', 'con_unidade'=>'(81) 3101-0287', 'con_unidade_2'=>'0287', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Serviço Social', 'con_unidade'=>'(81) 3101-0288', 'con_unidade_2'=>'0288', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coleta', 'con_unidade'=>'(81) 3101-0289', 'con_unidade_2'=>'0289', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Coordenação de Enfermagem', 'con_unidade'=>'(81) 3101-0290', 'con_unidade_2'=>'0290', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Administração', 'con_unidade'=>'(81) 3101-0291', 'con_unidade_2'=>'0291', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Nutrição', 'con_unidade'=>'(81) 3101-0292', 'con_unidade_2'=>'0292', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'SAME', 'con_unidade'=>'(81) 3101-0293', 'con_unidade_2'=>'0293', 'con_principal'=>'Interno', 'estabelecimento_id'=>95,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0370', 'con_unidade_2'=>'0370', 'con_principal'=>'Principal', 'estabelecimento_id'=>88,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0362', 'con_unidade_2'=>'0362', 'con_principal'=>'Principal', 'estabelecimento_id'=>89,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Infocras', 'con_unidade'=>'(81) 3101-0363', 'con_unidade_2'=>'0363', 'con_principal'=>'Interno', 'estabelecimento_id'=>89,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0403', 'con_unidade_2'=>'0403', 'con_principal'=>'Principal', 'estabelecimento_id'=>90,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0364', 'con_unidade_2'=>'0364', 'con_principal'=>'Principal', 'estabelecimento_id'=>96,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recepção', 'con_unidade'=>'(81) 3101-0217', 'con_unidade_2'=>'0217', 'con_principal'=>'Interno', 'estabelecimento_id'=>87,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Vigilância Ambiental', 'con_unidade'=>'(81) 3101-0216', 'con_unidade_2'=>'0216', 'con_principal'=>'Interno', 'estabelecimento_id'=>87,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Vigilância Sanitária', 'con_unidade'=>'(81) 3101-0215', 'con_unidade_2'=>'0215', 'con_principal'=>'Interno', 'estabelecimento_id'=>87,]);
        CompanyEstablishmentContactsModel::create([ 'dp_unidade'=>'Recursos Humanos', 'con_unidade'=>'(81) 3101-0218', 'con_unidade_2'=>'0218', 'con_principal'=>'Interno', 'estabelecimento_id'=>87,]);
    }
}
